W08D1/Reddit_clone_for_nubnub/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index]
end

#     subs GET   /subs(.:format)          subs#index
#          POST  /subs(.:format)          subs#create
#  new_sub GET   /subs/new(.:format)      subs#new
# edit_sub GET   /subs/:id/edit(.:format) subs#edit
#      sub GET   /subs/:id(.:format)      subs#show
#          PATCH /subs/:id(.:format)      subs#update
#          PUT   /subs/:id(.:format)      subs#update

# get 'posts/create'
# get 'posts/new'
# get 'posts/edit'
# get 'posts/show'
# get 'posts/update'
# get 'posts/destroy'
# get 'subs/new'
# get 'subs/edit'
# get 'subs/show'
# get 'subs/index'
# get 'subs/update'
# get 'subs/create'
# get 'sessions/new'
# get 'sessions/create'
# get 'sessions/destroy'
# get 'users/new'
# get 'users/create'

W08D1/Reddit_clone_for_nubnub/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditCloneForNubnub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%=flash[:errors]%>
    <%if logged_in?%>
      <%= current_user.username %>
      <form action= "<%=session_url%>" method = "post" >
      <input type="hidden" name = "authenticity_token" value = "<%=form_authenticity_token%>"  >

        <input type="hidden" name = "_method" value = "delete" >
        <input type="submit" value="Sign Out">
      </form>
      <br>
    <% end %>
    <%= yield %>

    <a href="<%=new_post_url%>">New Post</a>
  </body>
</html>