W08D1/Reddit_clone_for_nubnub/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index]
end

#     subs GET   /subs(.:format)          subs#index
#          POST  /subs(.:format)          subs#create
#  new_sub GET   /subs/new(.:format)      subs#new
# edit_sub GET   /subs/:id/edit(.:format) subs#edit
#      sub GET   /subs/:id(.:format)      subs#show
#          PATCH /subs/:id(.:format)      subs#update
#          PUT   /subs/:id(.:format)      subs#update

# get 'posts/create'
# get 'posts/new'
# get 'posts/edit'
# get 'posts/show'
# get 'posts/update'
# get 'posts/destroy'
# get 'subs/new'
# get 'subs/edit'
# get 'subs/show'
# get 'subs/index'
# get 'subs/update'
# get 'subs/create'
# get 'sessions/new'
# get 'sessions/create'
# get 'sessions/destroy'
# get 'users/new'
# get 'users/create'

W08D1/Reddit_clone_for_nubnub/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  
  validates :title, :description, :user_id, presence: true

  belongs_to :moderator,
    foreign_key: :user_id,
    class_name: :User 

    has_many :posts,
    foreign_key: :sub_id,
    class_name: :Post

    has_many :postsubs,
    foreign_key: :sub_id,
    class_name: :Postsub,
    inverse_of: :sub

    has_many :posts,
      through: :postsubs,
      source: :post

end

W08D1/Reddit_clone_for_nubnub/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :req_mod_login, only:[:edit, :update]

  def req_mod_login
    # Redirecting to stay consistent with other require_login method.
    # Redirect back to the sub they were on if they try to edit something they don't have access to
    render :show unless current_user.id == self.user_id 
  end

  def new 
    @sub = Sub.new
  end

  def edit
    @sub = Sub.find(params[:id]) # assuming routed this way based on current routes
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def index
    @subs = Sub.all
  end

  def update
    @sub = Sub.find(params[:id])
    @sub.update(sub_params) # receive from views
    flash[:errors] = @sub.errors.full_messages
    redirect_to sub_url(@sub)
  end

  def create  # nested new or create? NO. 
    @sub = Sub.new(sub_params) 
    @sub.user_id = current_user.id
    if @sub.save 
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages #, status: 418 # I forgot how to do these
      render :new
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description, :user_id)
  end
end

W08D1/Reddit_clone_for_nubnub/app/helpers/subs_helper.rb
module SubsHelper
end

W08D1/Reddit_clone_for_nubnub/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

W08D1/Reddit_clone_for_nubnub/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

W08D1/Reddit_clone_for_nubnub/app/views/subs/index.html.erb
<h1> Subs#index</h1>
<p>Find me in app/views/subs/index.html.erb</p>
All subs go hereeeeee
If you don't see this you done goofed

<a href="<%=new_sub_url%>">Make Your Own Sub</a>

<% @subs.each do |sub|%>
  <li><a href="<%=sub_url(sub)%>">"<%=sub.title%>"</a></li>
<% end %>

W08D1/Reddit_clone_for_nubnub/app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>


Make New Subs here

<form action="<%= subs_url %>" method="post">
<input type="hidden" name = "authenticity_token" value = "<%=form_authenticity_token%>"  >

  <label>Title
    <input type="text" name = "sub[title]">
  </label>

  <label>Description
    <input type="text" name = "sub[description]">
  </label>

  <input type="hidden" name="sub[user_id]" value="<%= current_user.id %>">
  
  <input type="submit" value="New Subreddit">

</form>

W08D1/Reddit_clone_for_nubnub/app/views/subs/show.html.erb
<h1>Subs#show</h1>
<p>Find me in app/views/subs/show.html.erb</p>

<li> <%= @sub.title %> </li>
<li> <%= @sub.description %> </li>
<li> link to edit later </li>

<a href= "<%=new_sub_url%>">Make a new sub here</a>
<br>
<a href="<%=subs_url%>">Take me home to all subs</a>

W08D1/Reddit_clone_for_nubnub/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>